name: Test & Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.10.4
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - name: test & build
        run: |
          pnpm test
          pnpm build
        env:
          CI: true
